elasticsearch:
  username: your_elasticsearch_username
  password: your_elasticsearch_password
  host: http://localhost
  port: 9200
rod:
  user_data_dir: "path_where_you_want_to_save_chrome_data"
  user_mode: false
  headless: false
  disable_blink_features: AutomationControlled
  incognito: false
  disable_dev_shm_usage: true
  no_sandbox: true
  default_page_width: 300
  default_page_height: 400
  user_agent: >-
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0
    Safari/537.36 Edg/142.0.0.0
  leakless: true
  bin: C:/Program Files/Google/Chrome/Application/chrome.exe
  disable_background_networking: false
  disable-background-timer-throttling: true
  disable-backgrounding-occluded-windows: true
  disable-renderer-backgrounding: true
  basic_remote_debugging_port: 9222
  trace: false
embedding:
  host: http://localhost
  port: 11434
  model: nomic-embed-text
llm:
  host: http://localhost
  port: 11434
  model: qwen3:1.7b